# Generated by Django 3.1.1 on 2020-10-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20201002_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='breeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=60)),
                ('breedname', models.CharField(max_length=67)),
            ],
        ),
    ]
