# Generated by Django 3.1.1 on 2020-10-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_breeds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breeds',
            old_name='petname',
            new_name='petsname',
        ),
    ]
