# Generated by Django 3.1.1 on 2020-10-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20201002_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='role',
        ),
    ]
