# Generated by Django 3.1.1 on 2020-10-29 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20201021_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breeds',
            name='petsname',
        ),
        migrations.AddField(
            model_name='breeds',
            name='petname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pets_sale',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
