# Generated by Django 3.1.1 on 2020-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20201029_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets_sale',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
