# Generated by Django 3.1.1 on 2020-11-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20201029_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets_sale',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pets_sale',
            name='image1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pets_sale',
            name='image2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pets_sale',
            name='image3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pets_sale',
            name='product_description',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pets_sale',
            name='product_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pets_sale',
            name='quantity',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pets_sale',
            name='breedname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
