# Generated by Django 3.1.1 on 2020-11-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_auto_20201124_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets_sale',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pets_sale',
            name='petname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
