# Generated by Django 3.1.1 on 2020-11-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_auto_20201124_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets_sale',
            name='name',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
