# Generated by Django 3.1.1 on 2020-12-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_auto_20201124_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets_sale',
            name='rating',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pets_sale',
            name='sex',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
