# Generated by Django 3.1.1 on 2020-11-22 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='birds_advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('bird_type', models.CharField(max_length=20)),
                ('pair_type', models.CharField(max_length=20)),
                ('dna_test', models.CharField(max_length=20)),
                ('ring', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='boarder_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('diet_plan', models.CharField(max_length=20)),
                ('boarding_days', models.CharField(max_length=20)),
                ('basic_training', models.CharField(max_length=20)),
                ('include_supplement', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='consultancy_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('pet', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('advice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='grooming_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('refferd_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='trainer_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('training_type', models.CharField(max_length=30)),
                ('others', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='transport_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('pickup_location', models.CharField(max_length=200)),
                ('drop_location', models.CharField(max_length=200)),
                ('transport_type', models.CharField(max_length=20)),
                ('pet_verification', models.CharField(max_length=20)),
                ('crate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vetnary_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('problem', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('medication_record', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='walker_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('timing', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('basic_training', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='dogs_advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('kci_certificate', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
