# Generated by Django 3.1.1 on 2020-11-23 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_auto_20201123_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=20, null=True)),
                ('breed', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100, null=True)),
                ('problem_description', models.CharField(max_length=150, null=True)),
                ('medication_record', models.ImageField(null=True, upload_to='')),
                ('diet_plan', models.CharField(max_length=20, null=True)),
                ('boarding_days', models.CharField(max_length=20, null=True)),
                ('basic_training', models.CharField(max_length=20, null=True)),
                ('include_supplement', models.CharField(max_length=20, null=True)),
                ('pickup_location', models.CharField(max_length=100, null=True)),
                ('drop_location', models.CharField(max_length=20, null=True)),
                ('transport_type', models.CharField(max_length=20, null=True)),
                ('pet_verification', models.CharField(max_length=20, null=True)),
                ('new_create', models.CharField(max_length=20, null=True)),
                ('current_pic', models.ImageField(null=True, upload_to='')),
                ('grooming_description', models.CharField(max_length=100, null=True)),
                ('refferd_pic', models.CharField(max_length=20, null=True)),
                ('timing', models.CharField(max_length=20, null=True)),
                ('walker_training', models.CharField(max_length=20, null=True)),
                ('training_type', models.CharField(max_length=20, null=True)),
                ('other', models.CharField(max_length=20, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
