# Generated by Django 3.1.1 on 2021-01-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201204_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=25)),
                ('specialist_for', models.CharField(max_length=25)),
                ('door_step', models.CharField(max_length=25)),
                ('certificate', models.ImageField(upload_to='')),
                ('cage_size', models.CharField(max_length=25)),
                ('diet_plan', models.CharField(max_length=25)),
                ('bathing', models.CharField(max_length=25)),
                ('vedio_time', models.CharField(max_length=25)),
                ('walk_time', models.CharField(max_length=25)),
                ('routes', models.CharField(max_length=250)),
                ('vehicle', models.CharField(max_length=25)),
                ('vehicle_number', models.CharField(max_length=25)),
                ('vehicle_type', models.CharField(max_length=10)),
                ('driving_lisence', models.ImageField(upload_to='')),
                ('aadhar_card', models.ImageField(upload_to='')),
                ('comfort', models.CharField(max_length=100)),
                ('working_hours', models.CharField(max_length=25)),
                ('timing', models.CharField(max_length=25)),
                ('address_proof', models.CharField(max_length=25)),
                ('boarding', models.CharField(max_length=25)),
                ('pre_work', models.FileField(max_length=250, upload_to='')),
            ],
        ),
    ]
